"""remove weather_data table and relationships

Revision ID: 682561d6e11f
Revises: c4002f802548
Create Date: 2025-03-31 02:46:07.137967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682561d6e11f'
down_revision = 'c4002f802548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_updated')

    op.drop_table('weather_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('humidity', sa.FLOAT(), nullable=True),
    sa.Column('rainfall', sa.FLOAT(), nullable=True),
    sa.Column('wind_speed', sa.FLOAT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location', name='uq_weather_location')
    )
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.create_index('ix_weather_updated', ['last_updated'], unique=False)

    # ### end Alembic commands ###
