"""Remove WeatherData model and relationships

Revision ID: b52a2c1d585f
Revises: 9fd4a55ee9af
Create Date: 2025-03-30 20:45:57.804632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52a2c1d585f'
down_revision = '9fd4a55ee9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('weather_data_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_data_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'weather_data', ['weather_data_id'], ['id'])

    # ### end Alembic commands ###
